# This is a basic workflow to help you get started with Actions

name: Update Equipment DB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
        - src/data/gear.json
        - src/scripts/update_equipment.ts
        - .github/workflows/update-equipment-db.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Check file differences
        run: |

          git remote set-url origin https://github:${{ secrets.GITHUB_TOKEN }}@github.com/adalundhe/lundhe-audio
          git fetch

          MAIN_REV=$(git rev-parse origin/main)
          CURRENT_REV=$(git rev-parse ${{ github.head_ref || github.ref_name }})

          if [[ $(git diff --exit-code $MAIN_REV $CURRENT_REV -- src/data/gear.json && echo $?) -gt 0 ]]; then
            echo "Gear updates detected..."
            echo "CHANGED=true" >>${GITHUB_ENV}
          else
            echo "No gear updates detected..."
            echo "CHANGED=false" >>${GITHUB_ENV}
          fi

      - uses: pnpm/action-setup@v4
        if: env.CHANGED == 'true'
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        if: env.CHANGED == 'true'
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also admits such aliases as lts/*, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        if: env.CHANGED == 'true'
        run: pnpm install 
      
      - name: Update Equipment Records
        if: env.CHANGED == 'true'
        env:
          TURSO_SQLITE_DB_DATABASE_URL: ${{ secrets.TURSO_SQLITE_DB_DATABASE_URL }}
          TURSO_SQLITE_DB_TOKEN: ${{ secrets.TURSO_SQLITE_DB_TOKEN }}
        shell: bash
        run: |
          pnpm db:update:equipment
          pnpm db:dump:equipment

      - name: Create Branch and Commit
        if: env.CHANGED == 'true'
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        run: |
          git config --global user.email "equipment.bot@lundhe.audio"
          git config --global user.name "EquipBot"

          git remote set-url origin https://github:${{ secrets.GITHUB_TOKEN }}@github.com/adalundhe/lundhe-audio

          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          if [[ "${{ github.ref }}" == "main" ]]; then
              git checkout -b update-equipment-${{ github.event.number }} || git checkout update-equipment-${{ github.event.number }}
              BRANCH_NAME="update-equipment-${{ github.event.number }}"
          fi

          git config pull.rebase false

          git add -A &&
          git commit -m "EquiBot: Syncing equipment"

          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Auto Merge PR
        if: env.CHANGED == 'true'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          gh pr create --head ${{ env.BRANCH_NAME }} --base main --title "Update Equipment ${{ github.event.number }}" --body "Updating equipment in gear.json" || true
          gh pr merge ${{ env.BRANCH_NAME }} --auto --merge --delete-branch
          
          
